#!/usr/bin/env python3

# @file config-pool-management is the executable used to interact with the ConfigPool class

import click
from Confpool import ConfPool


CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

@click.command(context_settings=CONTEXT_SETTINGS)
@click.argument('path', type=click.Path(exists=True, file_okay=False, writebla=True))

def cli(path) :





if __name__ == '__main__':
    cli(show_default=True, standalone_mode=True)
